# Generated by Django 3.0 on 2022-02-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='status',
        ),
    ]
