# Generated by Django 3.0 on 2022-02-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20220212_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='XL', max_length=3),
        ),
    ]
