# Generated by Django 3.0 on 2022-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20220213_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.CharField(choices=[('100-200', '100-200'), ('200-300', '200-300'), ('300-400', '300-400'), ('400-500', '400-500')], default='100-200', max_length=500),
        ),
    ]
