# Generated by Django 3.0 on 2022-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20220216_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='deresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
