# Generated by Django 3.0 on 2022-02-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contactss',
        ),
    ]
